---
name: CI

on: [push, pull_request]

jobs:
  test-name:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Generate App name
        id: app-name
        run: |
          repo_name=${{ github.event.repository.name }}
          repo_name='leed-option-II'
          clean_repo_name=${repo_name/-/ }
          echo "::set-output name=app_name::$clean_repo_name"
        

      - name: Check App name
        run: |
          echo "$APP_NAME"
      
        env:
         APP_NAME: ${{steps.app-name.outputs.app_name}}

  
  release-on-github:
    name: Deploy to GitHub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: set up node
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 14.2.0

      - name: install semantic-release
        run: npm install @semantic-release/exec

      - name: run semantic release
        id: new_release
        run: |
          nextRelease="`npx semantic-release@^17.0.0 --dryRun | grep -oP 'Published release \K.*? ' || true`"
          npx semantic-release@^17.0.0
          echo "::set-output name=tag::$nextRelease"

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    outputs:
      tag: ${{ steps.new_release.outputs.tag }}