---
name: CI

on: [push, pull_request]

jobs:
  test-name:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Generate App name
        id: app-name
        run: |
          repo_name=${{ github.event.repository.name }}
          clean_repo_name=${repo_name/-/ }
          echo "::set-output name=app_name::$clean_repo_name"
        

      - name: Check App name
        run: |
          echo "$APP_NAME"
      
        env:
         APP_NAME: ${{steps.app-name.outputs.app_name}}