---
name: CI

on: [push, pull_request]

jobs:
  test-name:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Generate App name
        run: |
          repo_name=${{ github.event.repository.name }}
          clean_repo_name=${repo_name/-/ }

      - name: Check App name
        run: |
          echo $CLEAN_REPO_NAME
      
        env:
         CLEAN_REPO_NAME: $clean_repo_name